apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress-image
        image: wordpress:php7.4-apache
        ports:
        - name: http-port
          containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: 127.0.0.1
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: db_password
      - name: mysql
        image: mysql:5.7
        ports:
          - name: mysql-port
            containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: db_password
