apiVersion: v1
kind: ReplicationController
metadata:
  name: replica-docker-demp
spec:
  replicas: 2
  selector:
    app: replica-docker-demp
  template:
    metadata:
      name: replica-docker-demp
      labels:
        app: replica-docker-demp
    spec:
      containers:
        - name: replica-docker-demp
          image: hashemirafsan/docker-demo
          ports:
          - name:  nodejs-port
            containerPort: 3000
